/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareerSimulatorRouteImport } from './routes/career-simulator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HrDashboardRouteImport } from './routes/hr-dashboard'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMyProfileRouteImport } from './routes/_authenticated/my-profile'
import { Route as EmployeeEmployeeIdRouteImport } from './routes/employee.$employeeId'
import { Route as RoleRoleIdRouteImport } from './routes/role.$roleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerSimulatorRoute = CareerSimulatorRouteImport.update({
  id: '/career-simulator',
  path: '/career-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDashboardRoute = HrDashboardRouteImport.update({
  id: '/hr-dashboard',
  path: '/hr-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyProfileRoute = AuthenticatedMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EmployeeEmployeeIdRoute = EmployeeEmployeeIdRouteImport.update({
  id: '/employee/$employeeId',
  path: '/employee/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoleIdRoute = RoleRoleIdRouteImport.update({
  id: '/role/$roleId',
  path: '/role/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/career-simulator': typeof CareerSimulatorRoute
  '/dashboard': typeof DashboardRoute
  '/hr-dashboard': typeof HrDashboardRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/hr': typeof AuthenticatedHrRoute
  '/me': typeof AuthenticatedMeRoute
  '/my-profile': typeof AuthenticatedMyProfileRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/role/$roleId': typeof RoleRoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/career-simulator': typeof CareerSimulatorRoute
  '/dashboard': typeof DashboardRoute
  '/hr-dashboard': typeof HrDashboardRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/hr': typeof AuthenticatedHrRoute
  '/me': typeof AuthenticatedMeRoute
  '/my-profile': typeof AuthenticatedMyProfileRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/role/$roleId': typeof RoleRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/career-simulator': typeof CareerSimulatorRoute
  '/dashboard': typeof DashboardRoute
  '/hr-dashboard': typeof HrDashboardRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/my-profile': typeof AuthenticatedMyProfileRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/role/$roleId': typeof RoleRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/auth'
    | '/career-simulator'
    | '/dashboard'
    | '/hr-dashboard'
    | '/privacy'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/skills'
    | '/hr'
    | '/me'
    | '/my-profile'
    | '/employee/$employeeId'
    | '/role/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/auth'
    | '/career-simulator'
    | '/dashboard'
    | '/hr-dashboard'
    | '/privacy'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/skills'
    | '/hr'
    | '/me'
    | '/my-profile'
    | '/employee/$employeeId'
    | '/role/$roleId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-assistant'
    | '/auth'
    | '/career-simulator'
    | '/dashboard'
    | '/hr-dashboard'
    | '/privacy'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/skills'
    | '/_authenticated/hr'
    | '/_authenticated/me'
    | '/_authenticated/my-profile'
    | '/employee/$employeeId'
    | '/role/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiAssistantRoute: typeof AiAssistantRoute
  AuthRoute: typeof AuthRoute
  CareerSimulatorRoute: typeof CareerSimulatorRoute
  DashboardRoute: typeof DashboardRoute
  HrDashboardRoute: typeof HrDashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  EmployeeEmployeeIdRoute: typeof EmployeeEmployeeIdRoute
  RoleRoleIdRoute: typeof RoleRoleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-simulator': {
      id: '/career-simulator'
      path: '/career-simulator'
      fullPath: '/career-simulator'
      preLoaderRoute: typeof CareerSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-dashboard': {
      id: '/hr-dashboard'
      path: '/hr-dashboard'
      fullPath: '/hr-dashboard'
      preLoaderRoute: typeof HrDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-profile': {
      id: '/_authenticated/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof AuthenticatedMyProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/employee/$employeeId': {
      id: '/employee/$employeeId'
      path: '/employee/$employeeId'
      fullPath: '/employee/$employeeId'
      preLoaderRoute: typeof EmployeeEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role/$roleId': {
      id: '/role/$roleId'
      path: '/role/$roleId'
      fullPath: '/role/$roleId'
      preLoaderRoute: typeof RoleRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMyProfileRoute: typeof AuthenticatedMyProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMyProfileRoute: AuthenticatedMyProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiAssistantRoute: AiAssistantRoute,
  AuthRoute: AuthRoute,
  CareerSimulatorRoute: CareerSimulatorRoute,
  DashboardRoute: DashboardRoute,
  HrDashboardRoute: HrDashboardRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  EmployeeEmployeeIdRoute: EmployeeEmployeeIdRoute,
  RoleRoleIdRoute: RoleRoleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
